### ISSUE TITLE
error

### ISSUE THREAD

**Issue by haszimoto** [ArmandSy/InstaLocTrack#5]
Traceback (most recent call last):
  File "/home/user/.local/bin/instaloctrack", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.9/site-packages/instaloctrack/instaloctrack.py", line 536, in main
    re.search("([0-9]+)</span> publications",
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Mrpolack** [comment]
same here! any fix?

**Comment by bernsteining** [comment]
Looks like instagram changed the layout of the page. Feel free to submit a PR to fix the bug :) I don't have time anymore to code this tool, and when I look at the code I want to rewrite it from scratch.
